# Generated by Django 2.2.3 on 2021-09-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('Profession', models.CharField(max_length=100)),
                ('current_address', models.CharField(max_length=200)),
                ('permanent_address', models.CharField(max_length=200)),
                ('nid_no', models.CharField(max_length=100)),
                ('Deposit_amount', models.FloatField()),
                ('tenure', models.FloatField()),
                ('opening_date', models.DateField()),
                ('photoFileName', models.CharField(max_length=100)),
            ],
        ),
    ]
