# Generated by Django 2.2.3 on 2021-09-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210926_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('total_balance', models.FloatField()),
                ('is_loan', models.BooleanField()),
                ('loan_amount', models.FloatField()),
                ('tenure', models.FloatField()),
                ('interest_rate', models.FloatField()),
            ],
        ),
    ]
